const mongoose = require('mongoose')

const AdminSchema = new mongoose.Schema({
    name: {
        type: String,
        required: [true, 'Please add a name']
    },
    email: {
        type: String,
        required: [true, 'Please add an email'],
        unique: true,
        match: [
            /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
            'Please add a valid email'
        ]
    },
    avatar: {
        type: String,
        default: null
    },
    position: {
        type: String,
        enum : [
            'UNASSIGNED',
            'ADMIN',
            'EDITOR',
            'CREATOR',
            'VIEWER'
        ],
        default: 'UNASSIGNED'
    },
    autoGenerated: {
        type: Boolean,
        default: false
    }
}, { timestamps: true })

module.exports = mongoose.model('Admin', AdminSchema)